# Generated by Django 4.2.3 on 2023-07-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Botania', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='color',
            new_name='tipoCatalogo',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='temporada',
        ),
    ]
