# Generated by Django 4.2.3 on 2023-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botania', '0003_rename_color_catalogo_tipocatalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
