# Generated by Django 4.2.3 on 2023-07-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Botania', '0004_alter_catalogo_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='tamaño',
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
